UV ?= uv
NPM ?= npm
MESSAGE ?= schema update
WEEKS ?= 1

define header

Project Tasks

Usage:

	make install       Install project and development dependencies
	make run           Run the local server
	make dev           Run the local server and Vite
	make db-start      Start PostgreSQL
	make db-stop       Stop PostgreSQL
	make db-seed       Generate 2-3 development measurements on 3-4 days per week
	make db-up         Apply all pending database migrations
	make db-current    Show the current database revision
	make db-down       Revert the latest database migration
	make db-rev        Create an autogenerated database migration
	make test          Run tests
	make lint          Run backend and frontend lint checks
	make format        Format backend and frontend code
	make format-check  Check backend and frontend formatting
	make typecheck     Type-check backend and frontend code
	make check         Run all quality checks and tests
	make build         Build frontend and Python distributions
	make openapi       Regenerate OpenAPI schema and frontend client

endef
export header

.PHONY: help
help:
	@echo "$$header"

.PHONY: sync
sync:
	$(UV) sync

.PHONY: install
install: sync
	$(NPM) --prefix frontend install

.PHONY: run
run:
	$(UV) run eufylocal

.PHONY: dev
dev:
	$(MAKE) -j2 run frontend-dev

.PHONY: frontend-dev
frontend-dev:
	$(NPM) --prefix frontend run dev

.PHONY: db-start
db-start:
	docker compose up -d --wait postgres

.PHONY: db-stop
db-stop:
	docker compose stop postgres

.PHONY: db-seed
db-seed:
	$(UV) run python -m eufylocal.scripts.seed --weeks $(WEEKS)

.PHONY: db-up
db-up:
	$(UV) run alembic -c eufylocal/db/alembic.ini upgrade head

.PHONY: db-current
db-current:
	$(UV) run alembic -c eufylocal/db/alembic.ini current

.PHONY: db-down
db-down:
	$(UV) run alembic -c eufylocal/db/alembic.ini downgrade -1

.PHONY: db-rev
db-rev:
	$(UV) run alembic -c eufylocal/db/alembic.ini revision --autogenerate -m "$(MESSAGE)"

.PHONY: test
test:
	$(UV) run pytest -q

.PHONY: lint
lint:
	$(UV) run ruff check .
	$(NPM) --prefix frontend run lint

.PHONY: format
format:
	$(UV) run ruff check --fix .
	$(UV) run ruff format .
	$(NPM) --prefix frontend run format

.PHONY: format-check
format-check:
	$(UV) run ruff format --check .
	$(NPM) --prefix frontend run format:check

.PHONY: typecheck
typecheck:
	$(UV) run pyright
	$(NPM) --prefix frontend run typecheck

.PHONY: check
check: lint format-check typecheck test

.PHONY: openapi
openapi:
	$(UV) run python eufylocal/scripts/openapi.py --app eufylocal.main:app
	$(NPM) --prefix frontend run openapi

.PHONY: build
build:
	$(NPM) --prefix frontend run build
	$(UV) build

.DEFAULT_GOAL := help
