UV ?= uv
HOST ?=
PORT ?=
TIMEOUT ?= 10
MESSAGE ?= schema update
WEEKS ?= 1

SERVE_ARGS = $(if $(HOST),--host $(HOST)) $(if $(PORT),--port $(PORT))

define header

Project Tasks

Usage:

	make install       Install project and development dependencies
	make run           Run the local server
	make scan          Scan BLE devices once
	make dump          Capture repeated T9146 BLE payloads
	make db-start      Start PostgreSQL
	make db-stop       Stop PostgreSQL
	make db-seed       Generate 3-4 development measurements per week
	make db-up         Apply all pending database migrations
	make db-current    Show the current database revision
	make db-down       Revert the latest database migration
	make db-rev        Create an autogenerated database migration
	make test          Run tests
	make lint          Run Ruff checks
	make format        Fix lint issues and format code
	make format-check  Check formatting without changes
	make typecheck     Run Pyright
	make check         Run all quality checks and tests
	make build         Build wheel and source distribution
	make openapi       regenerate OpenAPI schema

endef
export header

.PHONY: help
help:
	@echo "$$header"

.PHONY: sync
sync:
	$(UV) sync

.PHONY: run
run:
	$(UV) run eufylocal serve $(SERVE_ARGS)

.PHONY: scan
scan:
	$(UV) run eufylocal scan --timeout $(TIMEOUT)

.PHONY: dump
dump:
	$(UV) run eufylocal dump --timeout $(TIMEOUT)

.PHONY: db-start
db-start:
	docker compose up -d --wait postgres

.PHONY: db-stop
db-stop:
	docker compose stop postgres

.PHONY: db-seed
db-seed:
	$(UV) run python -m eufylocal.scripts.seed --weeks $(WEEKS)

.PHONY: db-up
db-up:
	$(UV) run alembic -c eufylocal/db/alembic.ini upgrade head

.PHONY: db-current
db-current:
	$(UV) run alembic -c eufylocal/db/alembic.ini current

.PHONY: db-down
db-down:
	$(UV) run alembic -c eufylocal/db/alembic.ini downgrade -1

.PHONY: db-rev
db-rev:
	$(UV) run alembic -c eufylocal/db/alembic.ini revision --autogenerate -m "$(MESSAGE)"

.PHONY: test
test:
	$(UV) run pytest -q

.PHONY: lint
lint:
	$(UV) run ruff check .

.PHONY: format
format:
	$(UV) run ruff check --fix .
	$(UV) run ruff format .

.PHONY: format-check
format-check:
	$(UV) run ruff format --check .

.PHONY: typecheck
typecheck:
	$(UV) run pyright

.PHONY: check
check: lint format-check typecheck test

.PHONY: openapi
openapi:
	$(UV) run python eufylocal/scripts/openapi.py --app eufylocal.main:app

.PHONY: build
build:
	$(UV) build

.DEFAULT_GOAL := help
