"""create measurements table

Revision ID: 43da97b30f1d
Revises:
Create Date: 2026-09-10 23:29:38.404984
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "43da97b30f1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("unit", sa.Enum("KG", "LB", name="measurementunit"), nullable=False),
        sa.Column("impedance_ohm", sa.Float(), nullable=True),
        sa.Column("raw_data", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "impedance_ohm IS NULL OR impedance_ohm > 0", name="ck_measurements_impedance_positive"
        ),
        sa.CheckConstraint("weight > 0", name="ck_measurements_weight_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_measurements_measured_at_id",
        "measurements",
        [sa.literal_column("measured_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_measurements_measured_at_id", table_name="measurements")
    op.drop_table("measurements")
    # ### end Alembic commands ###
