"""initial postgres schema

Revision ID: 89891b67bd1c
Revises:
Create Date: 2026-09-09 15:11:54.068000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89891b67bd1c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("impedance_ohm", sa.Float(), nullable=True),
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("raw_payload_hex", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_measurements_measured_at_id",
        "measurements",
        [sa.literal_column("measured_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_measurements_measured_at_id", table_name="measurements")
    op.drop_table("measurements")
    # ### end Alembic commands ###
