// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteMeasurementData,
  DeleteMeasurementErrors,
  DeleteMeasurementResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  GetLatestMeasurementData,
  GetLatestMeasurementErrors,
  GetLatestMeasurementResponses,
  GetMeasurementsData,
  GetMeasurementsErrors,
  GetMeasurementsResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  UpdateMeasurementData,
  UpdateMeasurementErrors,
  UpdateMeasurementResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Measurements
 */
export const getMeasurements = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeasurementsData, ThrowOnError>,
): RequestResult<GetMeasurementsResponses, GetMeasurementsErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetMeasurementsResponses, GetMeasurementsErrors, ThrowOnError>({
    url: "/api/measurements/",
    ...options,
  });

/**
 * Latest Measurement
 */
export const getLatestMeasurement = <ThrowOnError extends boolean = false>(
  options?: Options<GetLatestMeasurementData, ThrowOnError>,
): RequestResult<GetLatestMeasurementResponses, GetLatestMeasurementErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetLatestMeasurementResponses, GetLatestMeasurementErrors, ThrowOnError>({
    url: "/api/measurements/latest",
    ...options,
  });

/**
 * Delete Measurement
 */
export const deleteMeasurement = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMeasurementData, ThrowOnError>,
): RequestResult<DeleteMeasurementResponses, DeleteMeasurementErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteMeasurementResponses, DeleteMeasurementErrors, ThrowOnError>({
    url: "/api/measurements/{measurement_id}",
    ...options,
  });

/**
 * Update Measurement
 */
export const updateMeasurement = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMeasurementData, ThrowOnError>,
): RequestResult<UpdateMeasurementResponses, UpdateMeasurementErrors, ThrowOnError> =>
  (options.client ?? client).patch<UpdateMeasurementResponses, UpdateMeasurementErrors, ThrowOnError>({
    url: "/api/measurements/{measurement_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
): RequestResult<GetUsersResponses, GetUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({ url: "/api/users/", ...options });

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: "/api/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    url: "/api/users/{user_id}",
    ...options,
  });

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
  (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: "/api/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
