// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BLEStatus
 */
export type BleStatus = "idle" | "scanning" | "connecting" | "connected" | "error";

/**
 * BluetoothStatus
 */
export type BluetoothStatus = {
  status: BleStatus;
  /**
   * Device Id
   */
  device_id: string | null;
  /**
   * Device Name
   */
  device_name: string | null;
  /**
   * Last Error
   */
  last_error: string | null;
  /**
   * Live Weight Kg
   */
  live_weight_kg: number | null;
  /**
   * Live Weight Active
   */
  live_weight_active: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Measurement
 */
export type Measurement = {
  /**
   * Measured At
   */
  measured_at: string;
  /**
   * Weight Kg
   */
  weight_kg: number;
  /**
   * Impedance Ohm
   */
  impedance_ohm: number | null;
  /**
   * Device Id
   */
  device_id: string;
  /**
   * Source
   */
  source: "advertisement" | "gatt";
  /**
   * Raw Payload Hex
   */
  raw_payload_hex: string;
};

/**
 * Status
 */
export type Status = {
  bluetooth: BluetoothStatus;
  last_measurement: Measurement | null;
  /**
   * Server Time
   */
  server_time: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status";
};

export type GetStatusResponses = {
  /**
   * Successful Response
   */
  200: Status;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetMeasurementsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/measurements";
};

export type GetMeasurementsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMeasurementsError = GetMeasurementsErrors[keyof GetMeasurementsErrors];

export type GetMeasurementsResponses = {
  /**
   * Response Get Measurements
   *
   * Successful Response
   */
  200: Array<Measurement>;
};

export type GetMeasurementsResponse = GetMeasurementsResponses[keyof GetMeasurementsResponses];

export type GetLatestMeasurementData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/measurements/latest";
};

export type GetLatestMeasurementResponses = {
  /**
   * Response Get Latest Measurement
   *
   * Successful Response
   */
  200: Measurement | null;
};

export type GetLatestMeasurementResponse = GetLatestMeasurementResponses[keyof GetLatestMeasurementResponses];
