// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPError
 */
export type HttpError = {
  /**
   * Description
   */
  description: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Measurement
 */
export type Measurement = {
  /**
   * Id
   */
  id: number;
  /**
   * Measured At
   */
  measured_at: string;
  /**
   * Weight
   */
  weight: number;
  unit: MeasurementUnit;
  /**
   * Impedance Ohm
   */
  impedance_ohm: number | null;
  /**
   * Raw Data
   */
  raw_data: string;
  user: User | null;
};

/**
 * MeasurementUnit
 */
export type MeasurementUnit = "kg" | "lb";

/**
 * User
 */
export type User = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Color
   */
  color: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetMeasurementsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/measurements/";
};

export type GetMeasurementsErrors = {
  /**
   * Unauthorized
   */
  401: HttpError;
  /**
   * Forbidden
   */
  403: HttpError;
  /**
   * Not Found
   */
  404: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMeasurementsError = GetMeasurementsErrors[keyof GetMeasurementsErrors];

export type GetMeasurementsResponses = {
  /**
   * Response Get Measurements
   *
   * Successful Response
   */
  200: Array<Measurement>;
};

export type GetMeasurementsResponse = GetMeasurementsResponses[keyof GetMeasurementsResponses];

export type GetLatestMeasurementData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/measurements/latest";
};

export type GetLatestMeasurementErrors = {
  /**
   * Unauthorized
   */
  401: HttpError;
  /**
   * Forbidden
   */
  403: HttpError;
  /**
   * Not Found
   */
  404: HttpError;
};

export type GetLatestMeasurementError = GetLatestMeasurementErrors[keyof GetLatestMeasurementErrors];

export type GetLatestMeasurementResponses = {
  /**
   * Response Get Latest Measurement
   *
   * Successful Response
   */
  200: Measurement | null;
};

export type GetLatestMeasurementResponse = GetLatestMeasurementResponses[keyof GetLatestMeasurementResponses];

export type DeleteMeasurementData = {
  body?: never;
  path: {
    /**
     * Measurement Id
     */
    measurement_id: number;
  };
  query?: never;
  url: "/api/measurements/{measurement_id}";
};

export type DeleteMeasurementErrors = {
  /**
   * Unauthorized
   */
  401: HttpError;
  /**
   * Forbidden
   */
  403: HttpError;
  /**
   * Not Found
   */
  404: HttpError;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteMeasurementError = DeleteMeasurementErrors[keyof DeleteMeasurementErrors];

export type DeleteMeasurementResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteMeasurementResponse = DeleteMeasurementResponses[keyof DeleteMeasurementResponses];
